### ISSUE TITLE
host is null

### ISSUE THREAD

**Issue by karellm** [livereload/livereload-js#1]
Hi,

I have rack-livereload and guard-livereload installed in a Rails app setup as follow.

I have that setup in my `environment/development.`:

``` config.middleware.insert_before(
    Rack::Lock, Rack::LiveReload,
    :min_delay => 500,
    :max_delay => 10000,
    :port => 35729,
    :host => 'mywebsite.local'
  )
```

I have the following in my `views/layouts/application.html.erb`:
`<%= javascript_include_tag "http://mywebsite.local:35729/assets/lib/livereload.js" %>`

I've obviously restarted my server. I get the following console error:
`LiveReload cannot connect to null:35729, will retry in 60000 sec.`

I have my port 35729 listened by Apache and the js file is accessible.

I've tried to track down the problem without success. It is weird that the host is `null`. I've noticed that the regex for parsing the host is kinda broken. In my case (Rails), the path to the asset is `/assets/lib/livereload.js`; it generates a host as `mywebsite.local/assets/lib` when I would expect `mywebsite.local`.

In the `dist/livereload.js` on line 326, the regex is:
`/^[^:]+:\/\/(.*)\/z?livereload\.js(?:\?(.*))?$/`

when it should probably be:
`/^[^:]+:\/\/([^\/]+).*\/z?livereload\.js(?:\?(.*))?$/`

Do you have any idea of what is going on?

**Comment by andreyvit** [comment]
Actually I didn't mean to close it, #25 is only a workaround.
