### ISSUE TITLE
Bug: import, defer, async all fail due to static script tag regex

### ISSUE THREAD

**Issue by rayfoss** [livereload/livereload-js#102]
The following code runs, but returns  
`LiveReload disabled because it could not find its own <SCRIPT> tag`

```
<script type="module"> 
  const h = 'ctt5k-35729.sse.codesandbox.io'  
  import(\`https://\${h}/livereload.js\`)
</script>
```

This is also an issue with defer and async: https://stackoverflow.com/questions/49743015/gulp-errors-livereload-disabled-because-it-could-not-find-its-own-script-tag

## Workaround
https://github.com/livereload/livereload-js/blob/bb4f7ded85399e3e7eba8df454b37a319cafc44a/src/livereload.js

It looks like we only use script tag src information to infer the port and host of the websocker server.
Which is funny, because the reason I'm doing it dynamically is because it's hard to know that ahead of time.

**Comment by smhg** [comment]
Yes, you will have to use a <script> tag to your include livereload in your (dev) setup. Or use window.LiveReloadOptions to set parameters.

I don't see how the stackoverflow issue you are referring to has issues with defer and async? It seems similar in the way livereload is not included in a script tag. I didn't look at it properly but it seems to be an issue with gulp-connect?

Your 'workaround' refers to the livereload source code in general. I don't understand why you link to that.

Feel free to suggest other ways to set up the client. PRs are appreciated.
