### ISSUE TITLE
The js code is modified, causing the css code to become invalid

### ISSUE THREAD

**Issue by suiboyu** [livereload/livereload-js#112]
Operating environment：macOS 13.0.1 (22A400)、livereload：0.9.3

The following problems will appear in actual measurement. How to solve them?
1. When the css style is changed (such as changing the white background color to red), the foreground page will automatically refresh and the background will change to red, no problem.
2. But then I changed the title of the index.html page. After saving the title, the page was automatically refreshed, but the style was changed again (the background color was white again).

This is the code：
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="main.css">
</head>

<body>
  <script>
    document.title = 'bbbb'
  </script>
  <script>
    document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] +
      ':35729/livereload.js?snipver=1"></' + 'script>')
  </script>
</body>

</html>
```
main.css
```css
body {
    background-color: aqua;
}
```

**Comment by smhg** [comment]
@suiboyu Just a guess: your stylesheet is cached by your browser. I'd check its contents after the above 2 steps happen. Does it contain the correct value? Or it reverted to the original color?
You mention livereload 0.9.3. That [version](https://github.com/livereload/livereload-js/tags) doesn't even exist as far as I can tell. Please check your dependencies.
