### ISSUE TITLE
WebSocket port cannot be set to 80/443

### ISSUE THREAD

**Issue by steffenweber** [livereload/livereload-js#16]
livereload.js decides which WebSocket port to use by examining the `src` attribute of its `script` element (see [options.coffee](https://github.com/livereload/livereload-js/blob/master/src/options.coffee)). So if I load livereload.js on port 1234 then the WebSocket connection will use port 1234, too:

```
<script src="http://localhost:1234/livereload.js"></script>
```

Unfortunately, this does not work when using the standard HTTP/HTTPS 80/443 ports because browsers strip the default ports 80/443 from the `script` element's `src` attribute such that livereload.js does not see them (tested in Chrome 35 and Firefox 30). Therefore all three following embed methods use the fallback port 35729 instead of 80 or 443:

```
<script src="https://localhost:443/livereload.js?snipver=1"></script>
<script src="http://localhost:80/livereload.js?snipver=1"></script>
<script src="/livereload.js?snipver=1"></script>
```

I've setup livereload behind an nginx proxy on port 80/443 for two reasons:
1. Only ports 80/443 are needed and not port 35729 (firewall, port forwarding, ...).
2. I do not have to configure SSL/HTTPS in tiny-lr because SSL/HTTPS is already configured in nginx.

At the moment I've patched the livereload.js file to use the fallback port 80/443 instead of 35729 (see https://github.com/mklabs/tiny-lr/pull/45). But this may break existing setups. How can this be solved in a clean way? Maybe a new "keep-port=1" URL parameter?

**Comment by Akito13** [comment]
Exactly the same issue on Hugo v0.55.0-DEV.

**Comment by smhg** [comment]
Please report this to the Hugo project. As the solution described above has been applied previously.
