### ISSUE TITLE
New Strict Matching Mode

### ISSUE THREAD

**Issue by steffenweber** [livereload/livereload-js#17]
When livereload.js receives a `reload` command it tries to pick a "best match" from the resources in the current document (see [reloader.coffee](https://github.com/livereload/livereload-js/blob/master/src/reloader.coffee)). In some cases this causes unnecessary reloads.

Example: I have two CSS files, `main.css` and `main-ie8.css`. Only `main.css` is a resource in the current document. But when livereload.js receives a `reload` command for `main-ie8.css` it will pick `main.css` as "best match" and reload it unnecessarily.

I'd like to see a "strict matching mode" in livereload.js that does a strict byte-by-byte comparison of paths in the function `numberOfMatchingSegments`. I've locally replaced this function with the following code:

```
numberOfMatchingSegments = function(path1, path2) {
    return path1 === path2 ? 1 : 0;
}
```

This change relies on receiving exact paths via the `reload` command. I've therefore implemented a new `basePath` option for gulp-livereload: https://github.com/vohof/gulp-livereload/pull/31

Would you agree to adding a strict matching mode to livereload.js?

**Comment by smhg** [comment]
PR #41 added this option. Thanks for the suggestion!
