### ISSUE TITLE
Make livereload as node-module

### ISSUE THREAD

**Issue by Ann-Dederkal** [livereload/livereload-js#21]
It is impossible to use livereload-js as a dependency of some other module because it is not node-module. E.g. [tiny-lr](https://github.com/mklabs/tiny-lr) uses livereload and it is copied to the module so it is difficult to keep it latest.
So if it was possible to include this module as a dependency such issues would not appear.

Besides that there are a lot of forks that add package.json to livereload. That proves that it is necessary improvement.

**Comment by nemoDreamer** [comment]
:+1:, @Ann-Dederkal, I'm currently using napcs/node-livereload or guard/guard-livereload.

**Comment by Ann-Dederkal** [comment]
Thank you for your advice but I use modules which use livereload as copied file. If I used it separately I would use some other library

**Comment by nemoDreamer** [comment]
Yeah, I read that, sucks... Maybe nudge the creators of those modules to include livereload as an actual dependency?

**Comment by andreyvit** [comment]
Hey, I hear you. Looking at this.

**Comment by andreyvit** [comment]
LiveReload is now published on npm and Bower as `livereload-js`, see README. I've switched to building livereload.js using Browserify, so the published package should work with it.

Please let me know if this helps, or if additional changes are needed.

I also wonder _why_ you want it as part of your Browserify build. Don't you only use it in development? Can you please explain the use case?

**Comment by andreyvit** [comment]
Okay, I may be confused here because there was another ticket about Browserify, and I think this one actually isn't. Anyways, the published package also contains `dist/livereload.js`, so probably suits your needs.

**Comment by Ann-Dederkal** [comment]
Thank you for publishing your module to npm and Bower. That's exactly what I needed!
