### ISSUE TITLE
Browserified bundle generates a client-side error

### ISSUE THREAD

**Issue by jessehattabaugh** [livereload/livereload-js#31]
I am attempting to Browserify livereload-js like so;
```
var lr = require('livereload-js');
```
When I include the resulting bundle in a webpage I get the following error in Chrome 
```
Uncaught TypeError: Cannot read property 'addPlugin' of undefined
```
The error originates from https://github.com/livereload/livereload-js/blob/master/src/livereload.coffee#L133

I'm using Chrome 40.0.2214.93, Browserify 8.1.3, and node v0.10.28

Also on IE 11

**Comment by andreyvit** [comment]
Hey, I think I've fixed this — please try version 2.2.2. 

You do need to add a bit of extra stuff to your bundle, please [see the updated Browserify section in README](https://github.com/livereload/livereload-js/#installing-using-npm-and-browserify).
