### ISSUE TITLE
tag a release to include the wss fix?

### ISSUE THREAD

**Issue by jrobeson** [livereload/livereload-js#33]
I'm referring to this one: https://github.com/livereload/livereload-js/pull/29

**Comment by Steffen185** [comment]
I'd like to see a release that includes the wss fix, too.

**Comment by andreyvit** [comment]
Just released version 2.2.2.

**Comment by Steffen185** [comment]
Thank you!

**Comment by adambiggs** [comment]
> Just released version 2.2.2

Where is this release? I see the commit e1d943628005ad8d18a50ee1e8c29858ca748d10, but it's doesn't show up on Bower because there's no tag.
