### ISSUE TITLE
Internet Explorer 8

### ISSUE THREAD

**Issue by danilopopeye** [livereload/livereload-js#4]
Webpage error details
```
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Timestamp: Wed, 18 Jul 2012 21:33:18 UTC

Message: 'this.reloader' is null or not an object
Line: 956
Char: 5
Code: 0
URI: http://localhost:35729/livereload.js?snipver=1
````
I'm using the latest Beta: v2.3.14

**Comment by infn8** [comment]
You can use [Modernizr](http://modernizr.com) to guard against non supported browsers.  Take out your ```<script>``` tag that links to livereload.js and replace it with this
```html
<script>
Modernizr.load({
  test: Modernizr.websockets,
  yep : window.location.protocol + '//' + window.location.host + ':35729/livereload.js'
});
</script>
```
Assuming that you have the livereload.js available at the domain at port ```35729```.  Also remember that your modernizr build must test for websockets.
