### ISSUE TITLE
The connection to .. was interrupted while the page was loading

### ISSUE THREAD

**Issue by BabakMN** [livereload/livereload-js#40]
`The connection to ws://localhost:35729/livereload was interrupted while the page was loading.`

This warning appears in the console (Firefox 38, Linux) after a page reload is done.

It appears that livereload doesn't terminate the connection before the page unload.

I managed to get rid of the warning with the following snippet,

``` js
window.addEventListener('beforeunload', function(window){
    return function(){
        if (window.LiveReload){
            window.LiveReload.connector.socket.close();
        }
    }
}(window));
```

Any information on this?

**Comment by nathanhornby** [comment]
I'm also experiencing this. Having recently migrated to Firefox for development I;ve noticed that the plugin doesn't seem as 'stable' on FF as it does on Chrome

**Comment by julmot** [comment]
Same problem

**Comment by FelixAkk** [comment]
+1

**Comment by rkmax** [comment]
Same problem here

**Comment by joallard** [comment]
Please do, this is a major log polluter

**Comment by joallard** [comment]
![screen shot 2016-01-14 at 17 44 08](https://cloud.githubusercontent.com/assets/949482/12340040/770fd26e-bae6-11e5-8fae-f8ca000cdc0f.png)

**Comment by joallard** [comment]
Firefox can't establish a connection to the server at ws://localhost:35729/livereload.

**Comment by 3du4** [comment]
Same problem here.

**Comment by PunkHaz4rd** [comment]
Same here.

**Comment by elhoussine** [comment]
Now what?

**Comment by govijuan** [comment]
Me too in Firefox for mac OS El Capitán

**Comment by 3du4** [comment]
Since this was few months ago, I cannot recall 100% but I think updating to the latest version of node (used nvm) solved the issue.

**Comment by smhg** [comment]
Closing this as I'm not seeing it in Firefox 57. Feel free to comment should it still be the case for you.

**Comment by kherox** [comment]
same problem with firefox 60.0.2

**Comment by smhg** [comment]
@kherox can you please provide a bit more information?
What is the exact message, line, column,...

Thanks!
