### ISSUE TITLE
add svg to image reloading

### ISSUE THREAD

**Issue by evilebottnawi** [livereload/livereload-js#45]

**Comment by sly7-7** [comment]
Hello, is it something that should work as of today ?
I mean, I'm using livereload-js through ember-cli, and when svg files are touched, a full-reload page is requested. Would it be working by adding `svg` in the regex here: https://github.com/livereload/livereload-js/blob/master/src/reloader.js#L177 ?

**Comment by smhg** [comment]
@sly7-7 I think that would work if it is in the regex. Would you be able to send a PR?
The regex appears at least twice. Please put it in a constant so we only have to update it in one place.

**Comment by sly7-7** [comment]
@smhg 👍 I'll do that. Thank you for the answer
