### ISSUE TITLE
RemoteLiveReload doesn't work when CDN is on

### ISSUE THREAD

**Issue by leowebguy** [livereload/livereload-js#49]
Loooove LiveReload!! 

Not sure if this is an issue, or is just supposed to work like that...

I have RemoteLiveReload 0.0.46 running just fine, then I activated CDN (cloudflare) so Chrome RemoteLiveReload Extension stopped connecting...

**Comment by smhg** [comment]
@leowebguy thank you for closing an outdated issue.
