### ISSUE TITLE
Should we use livereload in production?

### ISSUE THREAD

**Issue by burakkilic** [livereload/livereload-js#51]
Hello;

Thank you for great library. 

I am using LiveReload in localhost. But in production, I don't know if I should use it. 

My code in index.html is:

```
<script>
document.write('<script src=' + location.protocol + '//' + location.host.split(':')[0] + ':35729/livereload.js></' + 'script>')
</script>
```

And error is: 

```
...com:35729/livereload.js net::ERR_CONNECTION_REFUSED
```

What should I do?

**Comment by smhg** [comment]
You [should probably not](https://github.com/livereload/livereload-js/blob/master/README.md#installing-using-npm-and-browserify) use livereload in production.
What use-case do you have for this?
