### ISSUE TITLE
Reload JS only if included on the page

### ISSUE THREAD

**Issue by wearhere** [livereload/livereload-js#59]
When the LiveReload client receives change notifications for CSS and images, it attempts to determine if those changes are relevant to the page and only reloads if they are. However, it doesn't do this for JS or other files, but rather [blindly reloads](https://github.com/livereload/livereload-js/blob/e1d943628005ad8d18a50ee1e8c29858ca748d10/dist/livereload.js#L777) the page.

This is problematic for build processes where an edit to a script that is included on the page may cause changes to other files that _aren't_ included on the page. (Perhaps you're editing a dependency of multiple build targets, or are generating sourcemaps alongside your scripts.)

I've developed a plugin that will intercept all changed JS and sourcemaps and only reload the page if the page includes a script tag with a matching filename: https://github.com/mixmaxhq/livereload-require-js-includes (So it
will never reload for a sourcemap change, the assumption there being that the
sourcemap would only have changed if the JS changed too.) Is this functionality that you'd consider bringing into the core project? It seems (perhaps naively?) like the way that LiveReload _should_ work.

The only downside I see is the difficulty of determining whether the JS is included on the page. My plugin currently only checks [the last path component](https://github.com/mixmaxhq/livereload-require-js-includes/blob/075f4941b4e111cd6633168c81a825fa91f3bb97/index.js#L18), but it appears like LiveReload includes a [sophisticated algorithm](https://github.com/livereload/livereload-js/blob/e1d943628005ad8d18a50ee1e8c29858ca748d10/dist/livereload.js#L719) for comparing paths and that could probably be employed here.

**Comment by amk221** [comment]
I too have this problem where the entire page is unnecessarily being re-loaded due to this line:
https://github.com/livereload/livereload-js/blob/e1d943628005ad8d18a50ee1e8c29858ca748d10/dist/livereload.js#L777

**Comment by smhg** [comment]
Am I right to assume this is specific to RequireJS?
And perhaps also for native ES6 modules.

**Comment by wearhere** [comment]
@smhg I'm not sure I understand your question, but this problem of unnecessary reloads could happen for any script included on the page, regardless of how that script was written.
