### ISSUE TITLE
Release 2.2.3

### ISSUE THREAD

**Issue by smhg** [livereload/livereload-js#69]
@andreyvit the PR's for the 2 most 'annoying' and easy to fix issues are merged.
Could you release a new patch version?
Please also run the tests (see below).

So it would be awesome if you could:
- Run `npm test`
- And if ok run:
  - `npm version patch`
  - `git push && git push --tags`
  - `npm publish`

Thank you!

_About the tests:_
`npm install` doesn't complete on my machine (Linux) because of an issue with building a dependency (node-jscoverage) of expresso. I'll look into that as a next step.

**Comment by andreyvit** [comment]
Done!

I've fixed the version of JSDOM, so now `npm install` works and all tests pass.
