### ISSUE TITLE
Consider replacing coffeescript with ES6 

### ISSUE THREAD

**Issue by smhg** [livereload/livereload-js#70]
Remaining TODO's:
- [x] add a compressed build with [terser](https://github.com/terser-js/terser)
- [x] update README
- [x] create a script to bump the `bower.json` version
- [x] remove Rakefile
- [x] add a script to create `test/html/browserified/bundle.js` from `test/html/browserified/main.js` for manual testing
- [x] use `main` with `dist` dir and `module` with `src` dir in package.json
- [x] remove `lib` and `lib-cov` directories if possible

**Comment by andreyvit** [comment]
I would absolutely love this. Also, let's simplify the code and the build process as much as humanly possible.

**Comment by andreyvit** [comment]
Just a note: I've started experimenting with this, using decaffeinate and a new stack based on rollup, buble and mocha. Not ready to commit yet, but going well. Will re-decaf any new changes you make, don't worry.

**Comment by smhg** [comment]
Also removed Grunt in that branch. No more security warnings in dev.

Remaining TODO's:
- [ ] create a script to bump the `bower.json` version
- [ ] remove Rakefile
- [ ] remove `lib` and `lib-cov` directories if possible
- [ ] add a script to create `test/html/browserified/bundle.js` from `test/html/browserified/main.js` for manual testing
- [ ] update README

**Comment by smhg** [comment]
I've prepared a `3.0.0-alpha.1` release which removes coffeescript.
