### ISSUE TITLE
Remove build result from git

### ISSUE THREAD

**Issue by smhg** [livereload/livereload-js#71]
Add /dist to .gitignore.

**Comment by smhg** [comment]
Add /dist to .gitignore but not .npmignore.

**Comment by andreyvit** [comment]
I think there are other projects pulling from `dist/livereload.js`. We can look into it and maybe replace with a downloadable file somewhere else. On the other hand — why? :-)

**Comment by smhg** [comment]
I didn't think of the consequences yet, only listed thoughts as issues.
But one reason would be to remove changes to `/dist` from the git log. That's just noise.

**Comment by smhg** [comment]
Let's indeed not remove it for now.
