### ISSUE TITLE
feedback.livereload.com is down

### ISSUE THREAD

**Issue by CyberShadow** [livereload/livereload-js#76]
Seems like all links to the knowledge base are currently broken (404). This includes the http://go.livereload.com/kb link from http://livereload.com/ , and the "LiveReload protocol" link from https://github.com/livereload/livereload-js/blob/master/README.md leading to http://help.livereload.com/kb/ecosystem/livereload-protocol.

**Comment by smhg** [comment]
@CyberShadow thanks for reporting this.
@andreyvit are there any plans to bring back the KB?

If not, specifically for the protocol, we could point to http://livereload.com/api/protocol/ in the README.

**Comment by smhg** [comment]
@CyberShadow I've updated the README link as described. Website changes can be reported in the [site's repo](https://github.com/livereload/livereload-site).
