### ISSUE TITLE
version is wrong in dist/livereload.js

### ISSUE THREAD

**Issue by samuelcolvin** [livereload/livereload-js#79]
https://github.com/livereload/livereload-js/blob/7b1b5a38e44d37c7feb8e63f89a92123628199e0/dist/livereload.js#L7

It looks like the version hasn't been updated since `v2.2.2`.

**Comment by samuelcolvin** [comment]
In the tagged release `2.3.0`.

**Comment by smhg** [comment]
Please give version `2.4.0` a try. From that version onwards, the version number is derived from package.json (so no more manual updates in source).
**Sidenote:** 2.4.0 was available on npm only. A release tag was missing, but I've [added that](https://github.com/livereload/livereload-js/releases/tag/v2.4.0).

**Comment by samuelcolvin** [comment]
Great, tag was what I needed since for aiohttp-devtools I download `livereload.js` directly from github.
