### ISSUE TITLE
default-src

### ISSUE THREAD

**Issue by caogaofeng0** [livereload/livereload-js#81]
Refused to load the script 'http://localhost:35729/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by smhg** [comment]
What this means is your project has [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) enabled.
You need to whitelist `localhost:35729` with a policy that includes:
```
script-src http://localhost:35729; connect-src ws://localhost:35729
```
This is not related to livereload-js.
