### ISSUE TITLE
feature request: provide option to omit port in <script/> call to livereload

### ISSUE THREAD

**Issue by laurencefass** [livereload/livereload-js#98]
I am running a livereload-js compliant server on the default livereload port behind an nginx reverse proxy exposed on port 80 which I am using to proxy requests back to livereload's default port. I want to configure the socket URL without a port so i can proxy according to my specific needs but i cant find a way to do it.

```
  <script>
    let script = '<script src="https://' + (location.host || 'localhost').split(':')[0] +
    '/livereload/livereload.js?snipver=1"></' + 'script>';
    document.write(script);
    console.log(script);
  </script>
```

results socket URLs with a :port configuration

**temporary workaround:**
I have altered code to remove the port from URI as it is not relevant to my setup.

e.g: removes the :port and my proxied livereload works.

`sed -i 's/concat(this.options.host, ":").concat(this.options.port, "\/")/concat(this.options.host, "\/")/g' /usr/local/share/.config/yarn/global/node_modules/livereload-js/dist/livereload.js `

any help or advice on easier ways to approach this most welcome.

thanks

**Comment by smhg** [comment]
Would it be a workaround to mention port 80 in the script url? Does it work for you in that case?

**Comment by laurencefass** [comment]
I am using a third party reverse docker proxy which is misdirecting any URL with a :port. 

I think :80 should work - but it doesn't.  I may be able to fix it through configuring the third party nginx configuration. However it would be great to make a port spec optional: ports are sometimes just not required when working with a  proxy.

**Comment by smhg** [comment]
@laurencefass this indeed sounds much more like a (configuration) issue in the software you use. A url:80 address isn't that special, no?

The alternative, adding an option (e.g. `doNotAppendPort`) to livereload-js to only prevent adding port 80 to URLs (a rare use case, which - i assume - still uses a correct format) sounds a bit overkill.

While I definitely might be wrong about the correct use of port 80 (please feel free to clarify), this currently does not seem like the right solution.

**Comment by laurencefass** [comment]
thanks for your feedback it may be a configuration issue with my letsencrypt/docker proxy setup, though im not sure that forcing a url:port spec is correct either. rather than add more config can the spec be derived from the client request?

**Comment by smhg** [comment]
@laurencefass I wish I could help you with this, but I have no relevant experience with nginx... Please don't hesitate to update this issue should this turn out to be expected behaviour. In that case we need to handle this better.

**Comment by smhg** [comment]
@iamFIREcracker I am unable to provide any feedback on this issue/your findings. Feel free to submit a PR in case you think something can be improved. I'm happy to merge any improvements.

**Comment by RolKau** [comment]
@iamFIREcracker @laurencefass
I encourage you to try the code in the livereload/livereload-js#110 branch. With this you should be able to do something like:
 
    <script src="/livereload.js?port="></script>

and have the script establish a web-socket back through the same proxy that was used to serve the web-page.
